[package]
name = "arclight"
version = "0.0.1"
authors = ["Chris Prohoda <cgprohoda@gmail.com>"]
license = "MIT/Apache-2.0"
description = "WIP crate for the arclight language"

[dependencies]
regex = "1"
lazy_static = "1.1.0"
